// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using haku_chat.DbContexts;

#nullable disable

namespace haku_chat.Migrations
{
    [DbContext(typeof(ChatDbContext))]
    [Migration("20221001170110_InitializeDB")]
    partial class InitializeDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("haku_chat.Models.ChatLoginUserModel", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name")
                        .HasColumnOrder(1);

                    b.Property<string>("HostName")
                        .HasColumnType("varchar(128)")
                        .HasColumnName("host_name")
                        .HasColumnOrder(4);

                    b.Property<string>("IpAddress")
                        .HasMaxLength(43)
                        .HasColumnType("varchar(43)")
                        .HasColumnName("ip_address")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime")
                        .HasColumnName("last_update")
                        .HasColumnOrder(10);

                    b.Property<DateTime?>("LoginTime")
                        .HasColumnType("datetime")
                        .HasColumnName("login_time")
                        .HasColumnOrder(8);

                    b.Property<DateTime?>("LogoutTime")
                        .HasColumnType("datetime")
                        .HasColumnName("logout_time")
                        .HasColumnOrder(9);

                    b.Property<string>("MachineName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("machine_name")
                        .HasColumnOrder(5);

                    b.Property<string>("OsName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("os_name")
                        .HasColumnOrder(6);

                    b.Property<ushort>("Status")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("status")
                        .HasColumnOrder(2);

                    b.Property<string>("UserAgent")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("user_agent")
                        .HasColumnOrder(7);

                    b.HasKey("Name");

                    b.ToTable("chat_login_user");
                });

            modelBuilder.Entity("haku_chat.Models.ChatLogModel", b =>
                {
                    b.Property<DateTime>("RegTime")
                        .HasColumnType("datetime")
                        .HasColumnName("reg_date")
                        .HasColumnOrder(1);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message")
                        .HasColumnOrder(4);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name")
                        .HasColumnOrder(2);

                    b.Property<ushort?>("NameColorId")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("name_color_id")
                        .HasColumnOrder(3);

                    b.HasKey("RegTime");

                    b.ToTable("chat_log");
                });

            modelBuilder.Entity("haku_chat.Models.ChatNameColorMasterModel", b =>
                {
                    b.Property<ushort>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("code")
                        .HasColumnOrder(3);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("name")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.ToTable("chat_name_color_master");
                });

            modelBuilder.Entity("haku_chat.Models.UserMasterModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(95)")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .HasColumnType("varchar(256)")
                        .HasColumnName("password");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("varchar(256)")
                        .HasColumnName("passwordhash");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("user_id")
                        .HasColumnOrder(2);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.ToTable("user_master");
                });
#pragma warning restore 612, 618
        }
    }
}
